// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydosmqkhlzfeyesccilt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlkb3NtcWtobHpmZXllc2NjaWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjk4MzMsImV4cCI6MjA2OTkwNTgzM30.ZMX_JMgpv8t_C7i6Ea5lFHqdmCqWbHRxWDF1FNtdOFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});